version: '3'

services:
   mysql:
     container_name: mysql
     image: mysql:8
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     ports:
       - "3306:3306"
     expose:
       - "3306" 
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: stack
       MYSQL_USER: root
       MYSQL_PASSWORD: password

   stack:
     depends_on:
       - mysql
     container_name: stack_app
     build:
       context: ./
       dockerfile: ./Dockerfile
     ports:
       - "8080:8080"
     expose:
       - "8080"
     environment:
       SPRING_PROFILES_ACTIVE: mysql
     restart: always
     
   sut:
     build:
       context: ./
       dockerfile: ./Dockerfile.test
     links:
       - stack
     
volumes:
    db_data: